# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prova2_DM_IOS_JoaoGabrielAmorimPadua' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prova2_DM_IOS_JoaoGabrielAmorimPadua

end
